dict_for_razmetka = {
    0: { 'name_group': 'Медицина',
        'candidates': ['поликлиника','больница'],
         'sm_score': 0.81},
    1: {'name_group': 'Удобная парковка',
        'candidates': ['парковка'],
        'sm_score': 0.838},
    2: {'name_group': 'Рекомендую +/-',
        'candidates': ['плохой','хорошо'],
        'sm_score': 0.87},
    3: {'name_group': 'Образование',
        'candidates': ['школа','университет'],
        'sm_score': 0.87},
    4: {'name_group': 'Сфера услуг',
        'candidates': ['маркет', 'магазины', 'парикмахерские'],
        'sm_score': 0.87},
    5: {'name_group': 'Обустроенность двора',
        'candidates': ['площадка', 'чистота','тренажеры'],
        'sm_score': 0.87},
    6: {'name_group': 'Коммунальные услуги',
        'candidates': ['электричество', 'отопление','вода'],
        'sm_score': 0.845},

}

